import { StyleSheet } from 'react-native';
import { COLORS, TYPOGRAPHY, SPACING } from '../../constants/design';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.neutral[50],
    alignItems: 'center',
    justifyContent: 'center',
    padding: SPACING.xl,
  },
  content: {
    alignItems: 'center',
    gap: SPACING.xl * 1.5,
  },
  wandContainer: {
    width: 160,
    height: 160,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  wandGlow: {
    position: 'absolute',
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: COLORS.primary[200],
    opacity: 0.3,
  },
  wandWrapper: {
    width: 80,
    height: 80,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.primary[50],
    borderRadius: 40,
    shadowColor: COLORS.primary[400],
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 20,
    elevation: 10,
    borderWidth: 2,
    borderColor: COLORS.primary[200],
  },
  magicParticle: {
    position: 'absolute',
    width: 16,
    height: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingText: {
    ...TYPOGRAPHY.body1,
    color: COLORS.primary[700],
    textAlign: 'center',
    fontWeight: '600',
    letterSpacing: 0.5,
  },
  progressContainer: {
    width: '100%',
    maxWidth: 300,
    alignItems: 'center',
    gap: SPACING.sm,
  },
  progressTrack: {
    width: '100%',
    height: 6,
    backgroundColor: COLORS.neutral[200],
    borderRadius: 3,
    overflow: 'hidden',
    position: 'relative',
  },
  progressFill: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    backgroundColor: COLORS.primary[500],
    borderRadius: 3,
  },
  progressGlow: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    backgroundColor: COLORS.primary[300],
    borderRadius: 3,
    filter: 'blur(4px)',
  },
  progressTextContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.xs,
    backgroundColor: COLORS.primary[50],
    paddingHorizontal: SPACING.sm,
    paddingVertical: SPACING.xs,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.primary[200],
  },
  progressText: {
    ...TYPOGRAPHY.caption,
    color: COLORS.primary[600],
    fontWeight: '600',
  },
});
