import { StyleSheet } from 'react-native';
import { COLORS, TYPOGRAPHY, SPACING } from '../../constants/design';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.neutral[50],
    alignItems: 'center',
    justifyContent: 'center',
    padding: SPACING.xl,
  },
  content: {
    alignItems: 'center',
    gap: SPACING.xl * 1.5,
  },
  wandContainer: {
    width: 240,
    height: 240,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  orbitalRing: {
    position: 'absolute',
    borderWidth: 2.5,
    borderRadius: 999,
    borderStyle: 'dashed',
    shadowColor: COLORS.primary[300],
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.6,
    shadowRadius: 10,
    elevation: 5,
  },
  wandGlow: {
    position: 'absolute',
    width: 160,
    height: 160,
    borderRadius: 80,
    opacity: 0.5,
    shadowColor: COLORS.primary[300],
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 30,
    elevation: 15,
  },
  wandWrapper: {
    width: 100,
    height: 100,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 50,
    shadowColor: COLORS.primary[400],
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 25,
    elevation: 15,
    borderWidth: 3,
    backgroundColor: COLORS.primary[50],
  },
  loadingText: {
    ...TYPOGRAPHY.body1,
    textAlign: 'center',
    fontWeight: '700',
    letterSpacing: 1,
    textShadowColor: 'rgba(0, 0, 0, 0.15)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
    fontSize: 18,
  },
  progressContainer: {
    width: '100%',
    maxWidth: 300,
    alignItems: 'center',
    gap: SPACING.sm,
  },
  progressTrack: {
    width: '100%',
    height: 8,
    backgroundColor: COLORS.neutral[200],
    borderRadius: 4,
    overflow: 'hidden',
    position: 'relative',
    shadowColor: COLORS.primary[300],
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 2,
  },
  progressFill: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    borderRadius: 4,
    shadowColor: COLORS.primary[400],
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 8,
    elevation: 4,
  },
  progressGlow: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    borderRadius: 4,
    filter: 'blur(6px)',
  },
  progressTextContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.xs,
    paddingHorizontal: SPACING.sm + 2,
    paddingVertical: SPACING.xs + 2,
    borderRadius: 14,
    borderWidth: 1.5,
    shadowColor: COLORS.primary[300],
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  progressText: {
    ...TYPOGRAPHY.caption,
    fontWeight: '700',
    fontSize: 14,
  },
});
